version: "3.8"
services:
  annotation_app:
    build: .  # build from Dockerfile in current directory
    volumes:
      - ./:/app  #
    restart: always
    ports:
      - "8008:8000"  # map port 8000 on host to port 8000 in container
    image: app:latest  # tag the image as app:latest
    container_name: annotation_app  # name the container as SWE574
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - annotation_db  # start the db container before starting the app container
  annotation_db:
    image: postgres:13-alpine  # use the latest postgres image
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"  # map port 8000 on host to port 8000 in container
    container_name: annotation_db
