# Generated by Django 4.1.3 on 2023-05-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_body',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotation_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotation_target',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotation_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='annotation',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation',
            field=models.JSONField(blank=True),
        ),
    ]
