# Generated by Django 4.1.3 on 2023-05-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_annotation_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation_body',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation_target',
            field=models.JSONField(blank=True),
        ),
    ]
